dataset: "trivia_qa"
split: "validation"
model: "gpt-3.5-turbo"
n_test: 100
do_perturb: true
n_perturb: 6
n_sample: 2
temperature: 1.0
max_tokens: 100
eigenvalues_threshold: 0.5
graph_mode: "entailment"
stop: null
prompt_type: "few_shot"
preload_responses: false
preload_accuracy: false
preload_uncertainty: false
preload_calibration: false
save_results: true
verbose: true